import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncSchema1765247618302 implements MigrationInterface {
    name = 'SyncSchema1765247618302'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT IF EXISTS "product_images_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "presentation" DROP CONSTRAINT IF EXISTS "fk_product"`);
        await queryRunner.query(`ALTER TABLE "sale_details" DROP CONSTRAINT IF EXISTS "fk_product"`);
        await queryRunner.query(`ALTER TABLE "sale_details" DROP CONSTRAINT IF EXISTS "fk_sale"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT IF EXISTS "fk_payment_method"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT IF EXISTS "fk_sale_status"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT IF EXISTS "fk_user"`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" SERIAL NOT NULL, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_price_history" ("id" SERIAL NOT NULL, "price" numeric(10,2) NOT NULL, "purchase_price" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "productId" integer, CONSTRAINT "PK_8ad05105010c053126d79113a5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_activity" ("id" SERIAL NOT NULL, "action" character varying NOT NULL, "metadata" json, "ip" character varying, "userAgent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_daec6d19443689bda7d7785dff5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN IF EXISTS "payment_method_id" CASCADE`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN IF EXISTS "sale_status_id" CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "presentation_id" integer`);
        await queryRunner.query(`ALTER TABLE "sale_details" ADD "presentation_id" integer`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "discount_applied" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "known_client" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "paymentMethod" character varying`);
        await queryRunner.query(`UPDATE "sales" SET "paymentMethod" = 'Efectivo' WHERE "paymentMethod" IS NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "paymentMethod" SET NOT NULL`);
        await queryRunner.query(`DO $$ BEGIN CREATE TYPE "public"."sales_salestatus_enum" AS ENUM('PENDING', 'COMPLETED', 'CANCELED'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "saleStatus" "public"."sales_salestatus_enum" DEFAULT 'PENDING'`);
        await queryRunner.query(`UPDATE "sales" SET "saleStatus" = 'PENDING' WHERE "saleStatus" IS NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "saleStatus" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "product_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "presentation" ALTER COLUMN "flavour" SET NOT NULL`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "products_id_seq" OWNED BY "products"."id"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "id" SET DEFAULT nextval('"products_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "name" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "purchase_price" TYPE numeric(10,2)`);
        await queryRunner.query(`UPDATE "products" SET "purchase_price" = 0 WHERE "purchase_price" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "purchase_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "purchase_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "description" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "display" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "image" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "stock" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "unidad_venta" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "unidad" SET DEFAULT 'u'`);
        await queryRunner.query(`UPDATE "products" SET "highlight" = '' WHERE "highlight" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "highlight" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "highlight" SET DEFAULT ''`);
        await queryRunner.query(`UPDATE "products" SET "informacion_nutricional" = '' WHERE "informacion_nutricional" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "informacion_nutricional" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "informacion_nutricional" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN IF EXISTS "display_order" CASCADE`);
        await queryRunner.query(`ALTER TABLE "products" ADD "display_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`UPDATE "products" SET "discount" = 0 WHERE "discount" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "discount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "discount" SET DEFAULT '0'`);
        await queryRunner.query(`UPDATE "products" SET "category" = '' WHERE "category" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "category" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "category" SET DEFAULT ''`);
        await queryRunner.query(`UPDATE "sale_details" SET "subtotal" = 0 WHERE "subtotal" IS NULL`);
        await queryRunner.query(`ALTER TABLE "sale_details" ALTER COLUMN "subtotal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN IF EXISTS "shipping" CASCADE`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "shipping" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "name" CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying`);
        await queryRunner.query(`UPDATE "users" SET "name" = 'User' WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "surname" CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "surname" character varying`);
        await queryRunner.query(`UPDATE "users" SET "surname" = '' WHERE "surname" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "surname" SET NOT NULL`);
        await queryRunner.query(`UPDATE "users" SET "address" = '{}' WHERE "address" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_mail_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "mail" CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mail" character varying`);
        await queryRunner.query(`UPDATE "users" SET "mail" = 'user' || id || '@example.com' WHERE "mail" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "mail" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_2e5b50f4b7c081eceea476ad128" UNIQUE ("mail")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "phone" CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`UPDATE "users" SET "phone" = '' WHERE "phone" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "password" CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying`);
        await queryRunner.query(`UPDATE "users" SET "password" = 'password' WHERE "password" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN IF EXISTS "role" CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying DEFAULT 'user'`);
        await queryRunner.query(`UPDATE "users" SET "role" = 'user' WHERE "role" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN IF EXISTS "name" CASCADE`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "name" character varying`);
        await queryRunner.query(`UPDATE "categories" SET "name" = 'Category' WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_a8fc559e734ed965376497e7785" FOREIGN KEY ("presentation_id") REFERENCES "presentation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presentation" ADD CONSTRAINT "FK_1d0b458f8ae4612ace81fa24f55" FOREIGN KEY ("product") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_details" ADD CONSTRAINT "FK_ff07d1ac574d56390cf66820fae" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_details" ADD CONSTRAINT "FK_245bcd4eb6fe045d6925d9a0a29" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_details" ADD CONSTRAINT "FK_7677134142fe9df9074f513a265" FOREIGN KEY ("presentation_id") REFERENCES "presentation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_5f282f3656814ec9ca2675aef6f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_7862b9a401e0fe7dc5ef96e9116" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_price_history" ADD CONSTRAINT "FK_64438a29390089f436eeeaae038" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_activity" ADD CONSTRAINT "FK_11108754ec780c670440e32baad" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_activity" DROP CONSTRAINT "FK_11108754ec780c670440e32baad"`);
        await queryRunner.query(`ALTER TABLE "product_price_history" DROP CONSTRAINT "FK_64438a29390089f436eeeaae038"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_7862b9a401e0fe7dc5ef96e9116"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_5f282f3656814ec9ca2675aef6f"`);
        await queryRunner.query(`ALTER TABLE "sale_details" DROP CONSTRAINT "FK_7677134142fe9df9074f513a265"`);
        await queryRunner.query(`ALTER TABLE "sale_details" DROP CONSTRAINT "FK_245bcd4eb6fe045d6925d9a0a29"`);
        await queryRunner.query(`ALTER TABLE "sale_details" DROP CONSTRAINT "FK_ff07d1ac574d56390cf66820fae"`);
        await queryRunner.query(`ALTER TABLE "presentation" DROP CONSTRAINT "FK_1d0b458f8ae4612ace81fa24f55"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_a8fc559e734ed965376497e7785"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(50) NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_2e5b50f4b7c081eceea476ad128"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "mail"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mail" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_mail_key" UNIQUE ("mail")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "surname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "surname" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sales" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "shipping"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "shipping" numeric`);
        await queryRunner.query(`ALTER TABLE "sale_details" ALTER COLUMN "subtotal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "category" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "category" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "discount" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "discount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "display_order"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "display_order" numeric`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "informacion_nutricional" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "informacion_nutricional" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "highlight" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "highlight" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "unidad" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "unidad_venta" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "stock" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "image" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "display" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "description" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "purchase_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "purchase_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "purchase_price" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "id" SET DEFAULT nextval('product_id_seq')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "products_id_seq"`);
        await queryRunner.query(`ALTER TABLE "presentation" ALTER COLUMN "flavour" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "product_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_images" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "saleStatus"`);
        await queryRunner.query(`DROP TYPE "public"."sales_salestatus_enum"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "known_client"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "discount_applied"`);
        await queryRunner.query(`ALTER TABLE "sale_details" DROP COLUMN "presentation_id"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "presentation_id"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "sale_status_id" integer`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "payment_method_id" integer`);
        await queryRunner.query(`DROP TABLE "user_activity"`);
        await queryRunner.query(`DROP TABLE "product_price_history"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_sale_status" FOREIGN KEY ("sale_status_id") REFERENCES "sale_status"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "fk_payment_method" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_details" ADD CONSTRAINT "fk_sale" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_details" ADD CONSTRAINT "fk_product" FOREIGN KEY ("product_id", "product") REFERENCES "product"("id","id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presentation" ADD CONSTRAINT "fk_product" FOREIGN KEY ("product_id", "product") REFERENCES "products"("id","id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "product_images_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
